{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "demo-app.labels" (dict "component" "backend" "global" .Values.global) | nindent 4 }}
spec:
  selector:
    {{- include "demo-app.selectorLabels" (dict "component" "backend") | nindent 4 }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      name: http
{{- end }}
