{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- include "demo-app.labels" (dict "component" "demo" "global" .Values.global) | nindent 4 }}
    {{- if .Values.namespace.istioAmbient }}
    istio.io/dataplane-mode: ambient
    {{- end }}
{{- end }}
